# Generated by Django 5.0.2 on 2024-03-02 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Название Продукта', max_length=100)),
                ('author', models.CharField(default='Автор', max_length=100)),
                ('start_datetime', models.DateTimeField()),
                ('price', models.IntegerField(default=100)),
                ('group_max', models.IntegerField(default=10)),
                ('group_min', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Имя студента', max_length=100)),
                ('password', models.CharField(default='Пароль', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Название урока', max_length=100)),
                ('link', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Название группы', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(through='product.StudentGroup', to='product.group'),
        ),
    ]
