# Generated by Django 5.0.2 on 2024-03-03 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='product.product'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='123', max_length=8),
        ),
        migrations.CreateModel(
            name='StudentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='product',
            field=models.ManyToManyField(through='product.StudentProduct', to='product.product'),
        ),
    ]
